const countriesWithNationality = [
    { country: 'Kenya', nationality: 'Kenyan', code: 'KE' },
    { country: 'United States', nationality: 'American', code: 'US' },
    { country: 'United Kingdom', nationality: 'British', code: 'GB' },
    { country: 'Canada', nationality: 'Canadian', code: 'CA' },
    { country: 'Australia', nationality: 'Australian', code: 'AU' },
    { country: 'Germany', nationality: 'German', code: 'DE' },
    { country: 'France', nationality: 'French', code: 'FR' },
    { country: 'Italy', nationality: 'Italian', code: 'IT' },
    { country: 'Spain', nationality: 'Spanish', code: 'ES' },
    { country: 'China', nationality: 'Chinese', code: 'CN' },
    { country: 'Japan', nationality: 'Japanese', code: 'JP' },
    { country: 'India', nationality: 'Indian', code: 'IN' },
    { country: 'South Africa', nationality: 'South African', code: 'ZA' },
    { country: 'Nigeria', nationality: 'Nigerian', code: 'NG' },
    { country: 'Ghana', nationality: 'Ghanaian', code: 'GH' },
    { country: 'Egypt', nationality: 'Egyptian', code: 'EG' },
    { country: 'Brazil', nationality: 'Brazilian', code: 'BR' },
    { country: 'Mexico', nationality: 'Mexican', code: 'MX' },
    { country: 'Russia', nationality: 'Russian', code: 'RU' },
    { country: 'South Korea', nationality: 'South Korean', code: 'KR' },
    { country: 'Netherlands', nationality: 'Dutch', code: 'NL' },
    { country: 'Sweden', nationality: 'Swedish', code: 'SE' },
    { country: 'Norway', nationality: 'Norwegian', code: 'NO' },
    { country: 'Denmark', nationality: 'Danish', code: 'DK' },
    { country: 'Finland', nationality: 'Finnish', code: 'FI' },
    { country: 'Switzerland', nationality: 'Swiss', code: 'CH' },
    { country: 'Austria', nationality: 'Austrian', code: 'AT' },
    { country: 'Belgium', nationality: 'Belgian', code: 'BE' },
    { country: 'Portugal', nationality: 'Portuguese', code: 'PT' },
    { country: 'Greece', nationality: 'Greek', code: 'GR' },
    { country: 'Turkey', nationality: 'Turkish', code: 'TR' },
    { country: 'Saudi Arabia', nationality: 'Saudi Arabian', code: 'SA' },
    { country: 'United Arab Emirates', nationality: 'Emirati', code: 'AE' },
    { country: 'Singapore', nationality: 'Singaporean', code: 'SG' },
    { country: 'Malaysia', nationality: 'Malaysian', code: 'MY' },
    { country: 'Thailand', nationality: 'Thai', code: 'TH' },
    { country: 'Vietnam', nationality: 'Vietnamese', code: 'VN' },
    { country: 'Philippines', nationality: 'Filipino', code: 'PH' },
    { country: 'Indonesia', nationality: 'Indonesian', code: 'ID' },
    { country: 'New Zealand', nationality: 'New Zealander', code: 'NZ' },
    { country: 'Ireland', nationality: 'Irish', code: 'IE' },
    { country: 'Poland', nationality: 'Polish', code: 'PL' },
    { country: 'Czech Republic', nationality: 'Czech', code: 'CZ' },
    { country: 'Hungary', nationality: 'Hungarian', code: 'HU' },
    { country: 'Romania', nationality: 'Romanian', code: 'RO' },
    { country: 'Ukraine', nationality: 'Ukrainian', code: 'UA' },
    { country: 'Argentina', nationality: 'Argentinian', code: 'AR' },
    { country: 'Chile', nationality: 'Chilean', code: 'CL' },
    { country: 'Colombia', nationality: 'Colombian', code: 'CO' },
    { country: 'Peru', nationality: 'Peruvian', code: 'PE' },
    { country: 'Venezuela', nationality: 'Venezuelan', code: 'VE' },
    { country: 'Pakistan', nationality: 'Pakistani', code: 'PK' },
    { country: 'Bangladesh', nationality: 'Bangladeshi', code: 'BD' },
    { country: 'Sri Lanka', nationality: 'Sri Lankan', code: 'LK' },
    { country: 'Nepal', nationality: 'Nepalese', code: 'NP' },
    { country: 'Myanmar', nationality: 'Burmese', code: 'MM' },
    { country: 'Cambodia', nationality: 'Cambodian', code: 'KH' },
    { country: 'Laos', nationality: 'Lao', code: 'LA' },
    { country: 'Mongolia', nationality: 'Mongolian', code: 'MN' },
    { country: 'Kazakhstan', nationality: 'Kazakh', code: 'KZ' },
    { country: 'Uzbekistan', nationality: 'Uzbek', code: 'UZ' },
    { country: 'Azerbaijan', nationality: 'Azerbaijani', code: 'AZ' },
    { country: 'Georgia', nationality: 'Georgian', code: 'GE' },
    { country: 'Armenia', nationality: 'Armenian', code: 'AM' },
    { country: 'Israel', nationality: 'Israeli', code: 'IL' },
    { country: 'Jordan', nationality: 'Jordanian', code: 'JO' },
    { country: 'Lebanon', nationality: 'Lebanese', code: 'LB' },
    { country: 'Syria', nationality: 'Syrian', code: 'SY' },
    { country: 'Iraq', nationality: 'Iraqi', code: 'IQ' },
    { country: 'Iran', nationality: 'Iranian', code: 'IR' },
    { country: 'Afghanistan', nationality: 'Afghan', code: 'AF' },
    { country: 'Morocco', nationality: 'Moroccan', code: 'MA' },
    { country: 'Algeria', nationality: 'Algerian', code: 'DZ' },
    { country: 'Tunisia', nationality: 'Tunisian', code: 'TN' },
    { country: 'Libya', nationality: 'Libyan', code: 'LY' },
    { country: 'Sudan', nationality: 'Sudanese', code: 'SD' },
    { country: 'Ethiopia', nationality: 'Ethiopian', code: 'ET' },
    { country: 'Somalia', nationality: 'Somali', code: 'SO' },
    { country: 'Uganda', nationality: 'Ugandan', code: 'UG' },
    { country: 'Tanzania', nationality: 'Tanzanian', code: 'TZ' },
    { country: 'Rwanda', nationality: 'Rwandan', code: 'RW' },
    { country: 'Burundi', nationality: 'Burundian', code: 'BI' },
    { country: 'Zambia', nationality: 'Zambian', code: 'ZM' },
    { country: 'Zimbabwe', nationality: 'Zimbabwean', code: 'ZW' },
    { country: 'Mozambique', nationality: 'Mozambican', code: 'MZ' },
    { country: 'Angola', nationality: 'Angolan', code: 'AO' },
    { country: 'Botswana', nationality: 'Motswana', code: 'BW' },
    { country: 'Namibia', nationality: 'Namibian', code: 'NA' },
    { country: 'Senegal', nationality: 'Senegalese', code: 'SN' },
    { country: 'Mali', nationality: 'Malian', code: 'ML' },
    { country: 'Niger', nationality: 'Nigerien', code: 'NE' },
    { country: 'Chad', nationality: 'Chadian', code: 'TD' },
    { country: 'Cameroon', nationality: 'Cameroonian', code: 'CM' },
    { country: 'Gabon', nationality: 'Gabonese', code: 'GA' },
    { country: 'Congo', nationality: 'Congolese', code: 'CG' },
    { country: 'DR Congo', nationality: 'Congolese', code: 'CD' },
    { country: 'Ivory Coast', nationality: 'Ivorian', code: 'CI' },
    { country: 'Liberia', nationality: 'Liberian', code: 'LR' },
    { country: 'Sierra Leone', nationality: 'Sierra Leonean', code: 'SL' },
    { country: 'Gambia', nationality: 'Gambian', code: 'GM' },
    { country: 'Guinea', nationality: 'Guinean', code: 'GN' },
    { country: 'Benin', nationality: 'Beninese', code: 'BJ' },
    { country: 'Togo', nationality: 'Togolese', code: 'TG' },
    { country: 'Burkina Faso', nationality: 'Burkinabe', code: 'BF' },
    { country: 'Mauritania', nationality: 'Mauritanian', code: 'MR' },
    { country: 'Mauritius', nationality: 'Mauritian', code: 'MU' },
    { country: 'Madagascar', nationality: 'Malagasy', code: 'MG' },
    { country: 'Seychelles', nationality: 'Seychellois', code: 'SC' },
    { country: 'Comoros', nationality: 'Comorian', code: 'KM' },
    { country: 'Djibouti', nationality: 'Djiboutian', code: 'DJ' },
    { country: 'Eritrea', nationality: 'Eritrean', code: 'ER' },
    { country: 'Malawi', nationality: 'Malawian', code: 'MW' },
    { country: 'Lesotho', nationality: 'Mosotho', code: 'LS' },
    { country: 'Eswatini', nationality: 'Swazi', code: 'SZ' },
];

export default countriesWithNationality;